name = "chef-dashboard-update-recipes"
main = "src/index.mjs"
compatibility_date = "2026-02-22"

[vars]
GITHUB_BRANCH = "main"
GH_OWNER = "Carlosrosado13"
GH_REPO = "Chef-Dashboard"
GH_WORKFLOW_FILE = "apply-recipe-patch.yml"
GH_REF = "main"
